### ISSUE TITLE
Maybe we should use govalidator for structs validation

### ISSUE THREAD

**Issue by nmerkulov** [oasgo/oasgo#4]
At this moment we generate no checks for handlers structs. For example we dont check required fields or fields formats. This can be easily implemented via https://github.com/asaskevich/govalidator

**Comment by droptheplot** [comment]
>For example we dont check required fields or fields formats.

Are you sure this shouldn't be user responsibility?

**Comment by nmerkulov** [comment]
yep, i'm sure

we talking not about business specific stuff. If spec tells us that field a.FancyField is required, we can generate code performs such checks. thats about "interface specific". that's not much but helps a lot
